collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#2F3028'
    - '#EAE9E9'
    - '#884B39'
    - '#E0ACA3'
    - '#30BC9A'
  rhythmicContrast: 1
typography_spectrum: 0.3996416
layout_spectrum: 0
name: LowKeyCreative
